//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger_Web_App_Assignment.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignEmployee
    {
        public int ID { get; set; }
        public int EID { get; set; }
        public int RID { get; set; }
        public int CRID { get; set; }
        public string RName { get; set; }
        public string RLocation { get; set; }
        public System.DateTime MaxPreservedTime { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual CollectRequest CollectRequest { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
