//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger_Web_App_Assignment.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollectRequest()
        {
            this.AssignEmployees = new HashSet<AssignEmployee>();
        }
    
        public int ID { get; set; }
        public System.DateTime PresentTime { get; set; }
        public System.DateTime MaxPreservedTime { get; set; }
        public string Location { get; set; }
        public int ForHowManyPersons { get; set; }
        public string Status { get; set; }
        public int RID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignEmployee> AssignEmployees { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
